apiVersion: v1
kind: Service
metadata:
  name: rabbit
  labels:
    app: rabbit
spec:
  ports:
    - name: "5672"
      port: 5672
      targetPort: 5672
  selector:
    app: rabbit
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rabbit
  name: rabbit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbit
  strategy: {}
  template:
    metadata:
      labels:
        app: rabbit
    spec:
      containers:
        - image: rabbitmq:3-management
          imagePullPolicy: ""
          name: rabbit
          ports:
            - containerPort: 5672
          resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: gateway
  name: gateway
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    app: gateway
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  strategy: {}
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - env:
            - name: RABBIT_HOST
              value: rabbit
            - name: RABBIT_PASSWORD
              value: guest
            - name: RABBIT_PORT
              value: "5672"
            - name: RABBIT_USER
              value: guest
          image: etansoclof/q_gateway:6.2
          imagePullPolicy: ""
          name: gateway
          ports:
            - containerPort: 5000
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: process
  labels:
    app: process
spec:
  replicas: 1
  selector:
    matchLabels:
      app: process
  template:
    metadata:
      labels:
        app: process
    spec:
      containers:
        - env:
            - name: RABBIT_HOST
              value: rabbit
            - name: RABBIT_PASSWORD
              value: guest
            - name: RABBIT_PORT
              value: "5672"
            - name: RABBIT_USER
              value: guest
          image: etansoclof/q_process:6.0
          imagePullPolicy: ""
          name: process
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
